let current=0;let answers=JSON.parse(localStorage.getItem('clepAnswers')||'{}');
const $=id=>document.getElementById(id);
function norm(v){return String(v||'').toLowerCase().replace(/\s+/g,'').replace(/\$/g,'').replace(/cups?/g,'').replace(/milesperhour/g,'mph').replace(/percent/g,'%').trim()}
function save(){localStorage.setItem('clepAnswers',JSON.stringify(answers))}
function isCorrect(q,v){return(q.accepted||[q.answer]).map(norm).includes(norm(v))}
function renderNav(){const grid=$('navGrid');grid.innerHTML='';QUESTIONS.forEach((q,i)=>{const b=document.createElement('button');b.textContent=i+1;if(i===current)b.classList.add('current');if(answers[i])b.classList.add('done');b.onclick=()=>{current=i;render();window.scrollTo({top:0,behavior:'smooth'})};grid.appendChild(b)})}
function updateProgress(){const answered=Object.values(answers).filter(Boolean).length;$('answeredText').textContent=`${answered} answered`;$('answerMeter').style.width=`${answered/QUESTIONS.length*100}%`}
function render(){if(!window.QUESTIONS||!QUESTIONS.length){$('qText').textContent='Question bank did not load.';return}const q=QUESTIONS[current];$('topicBadge').textContent=q.topic;$('counter').textContent=`Question ${current+1} of ${QUESTIONS.length}`;$('progressText').textContent=`${current+1} of ${QUESTIONS.length}`;$('qNum').textContent=`${current+1}.`;$('qText').textContent=q.q;$('questionMeter').style.width=`${(current+1)/QUESTIONS.length*100}%`;updateProgress();const area=$('answerArea');area.innerHTML='';if(q.type==='mc'){q.choices.forEach((choice,idx)=>{const btn=document.createElement('button');btn.className='choice'+(answers[current]===choice?' selected':'');btn.innerHTML=`<span class="letter">${String.fromCharCode(65+idx)}</span><span>${choice}</span>`;btn.onclick=()=>{answers[current]=choice;save();render()};area.appendChild(btn)})}else{const input=document.createElement('input');input.className='answer';input.placeholder='Type your answer';input.value=answers[current]||'';input.oninput=()=>{answers[current]=input.value;save();renderNav();updateProgress()};area.appendChild(input)}renderNav()}
function prev(){if(current>0){current--;render();window.scrollTo({top:0,behavior:'smooth'})}}
function next(){if(current<QUESTIONS.length-1){current++;render();window.scrollTo({top:0,behavior:'smooth'})}}
function clearAnswers(){if(confirm('Clear all answers?')){answers={};save();current=0;$('resultsCard').classList.add('hidden');render()}}
function readiness(score){if(score>=23)return'Ready for full-length CLEP practice exams.';if(score>=20)return'Very close. Review weak areas and retest.';if(score>=15)return'Good foundation, but targeted review is needed.';if(score>=10)return'Significant review recommended before testing.';return'Build arithmetic and algebra foundations first.'}
function scoreExam(){let score=0;const topics={};const missed=[];QUESTIONS.forEach((q,i)=>{topics[q.topic] ||= {correct:0,total:0};topics[q.topic].total++;if(isCorrect(q,answers[i])){score++;topics[q.topic].correct++}else missed.push({num:i+1,q,your:answers[i]||'(blank)'})});let html=`<h2>Results</h2><div class="score ${score>=20?'good':'bad'}">${score}/25</div><p><strong>${Math.round(score/25*100)}%</strong> — ${readiness(score)}</p><h3>Topic Breakdown</h3><table><tr><th>Topic</th><th>Score</th><th>Percent</th></tr>`;Object.entries(topics).forEach(([t,d])=>{html+=`<tr><td>${t}</td><td>${d.correct}/${d.total}</td><td>${Math.round(d.correct/d.total*100)}%</td></tr>`});html+='</table><h3>Study Priority</h3><ol>';Object.entries(topics).sort((a,b)=>(a[1].correct/a[1].total)-(b[1].correct/b[1].total)).forEach(([t,d])=>{html+=`<li><strong>${t}</strong> — review until you can score at least 80%.</li>`});html+='</ol>';if(missed.length){html+='<h3>Missed Question Review</h3>';missed.forEach(m=>{html+=`<div class="reviewItem"><strong>Question ${m.num}:</strong> ${m.q.q}<br><strong>Your answer:</strong> ${m.your}<br><strong>Correct answer:</strong> ${m.q.answer}<br><strong>Why:</strong> ${m.q.explanation}</div>`})}else html+='<h3>Perfect score. No missed questions.</h3>';$('resultsCard').innerHTML=html;$('resultsCard').classList.remove('hidden');$('resultsCard').scrollIntoView({behavior:'smooth'})}
$('prevBtn').onclick=prev;$('nextBtn').onclick=next;$('scoreBtn').onclick=scoreExam;$('clearBtn').onclick=clearAnswers;$('printBtn').onclick=()=>window.print();render();